        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 02 10:43:25 2018
        MODULE INPUTEM__genmod
          INTERFACE 
            SUBROUTINE INPUTEM
            END SUBROUTINE INPUTEM
          END INTERFACE 
        END MODULE INPUTEM__genmod
