        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 02 10:43:25 2018
        MODULE INPUTKP__genmod
          INTERFACE 
            SUBROUTINE INPUTKP
            END SUBROUTINE INPUTKP
          END INTERFACE 
        END MODULE INPUTKP__genmod
